# keycloak-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: ecomAppkeycloak
  POSTGRES_PASSWORD: ecommApp@1122
