apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  labels:
    app: keycloak
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 8080  # Keycloak container port
