apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - image: prasadg2911/eureka-server:latest
          imagePullPolicy: Always
          name: eureka-server-container


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-server
  name: eureka-server
  namespace: default
spec:
  ports:
    - name: eureka
      port: 8761
      targetPort: 8761
  selector:
    app: eureka-server
  type: ClusterIP

