apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - image: prasadg2911/gateway-service:v10
          imagePullPolicy: Always
          name: gateway-service-container
          env: 
            - name: EUREKA_URL
              value: http://eureka-server:8761/eureka/
            - name: CONFIG_SERVER_URL
              value: http://config-service:8500
          envFrom:
            - secretRef:
                name: generic-secret


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-service
  name: gateway-service
  namespace: default
spec:
  ports:
    - name: config
      port: 8400
      targetPort: 8400
  selector:
    app: gateway-service
  type: LoadBalancer

