apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: prasadg2911/user-service:latest
          imagePullPolicy: IfNotPresent
          name: user-service-container
          env: 
            - name: EUREKA_URL
              value: http://eureka-server:8761/eureka/
            - name: CONFIG_SERVER_URL
              value: http://config-service:8500


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: default
spec:
  ports:
    - name: config
      port: 8000
      targetPort: 8000
  selector:
    app: user-service
  type: ClusterIP

