server:
  port: 8400
spring:
  application:
    name: gateway-service
#  main:
#    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springboot-microservice-realm
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: http://localhost:8000 #User
#              predicates:
#                - Path=/users/**
#            - id: order-service
#              uri: http://localhost:8100 #Order
#              predicates:
#                - Path=/orders/**
#            - id: product-service
#              uri: http://localhost:8300 #Product
#              predicates:
#                - Path=/products/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/