server:
  port: 8400
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/microservices-realm
    cloud:
      gateway:
        routes:
          - id: user-service
            uri: http://localhost:8000 #User
            predicates:
              - Path=/users/**
          - id: order-service
            uri: http://localhost:8100 #Order
            predicates:
              - Path=/orders/**
          - id: order-service
            uri: http://localhost:8300 #Product
            predicates:
              - Path=/products/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/