server:
  port: 8400
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/microservices-realm
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service #User
              predicates:
                - Path=/users/**
            - id: order-service
              uri: lb://order-service #Order
              predicates:
                - Path=/orders/**
            - id: product-service
              uri: lb://product-service #Product
              predicates:
                - Path=/products/**
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1