server:
  port: 8400
keycloak:
  auth-server-url: http://keycloak:8085
  realm: microservices-realm
  client-id: microservice-auth
  client-secret: ZBmO01ZhDpeC3hMb9TLWis5koJSciOl8
spring:
  application:
    name: gateway-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8085/realms/microservices-realm
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8000 #User
          predicates:
            - Path=/users/**
        - id: order-service
          uri: http://order-service:8200 #Order
          predicates:
            - Path=/orders/**
        - id: product-service
          uri: http://product-service:8300 #Product
          predicates:
            - Path=/products/**
management:
  endpoints:
    web:
      exposure:
        include: gateway,health,info
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
#  instance:
#    prefer-ip-address: true
#    ip-address: 127.0.0.1