# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-secret
type: Opaque
stringData:
  POSTGRES_DB: userdb
  POSTGRES_USER: ecommAppUser
  POSTGRES_PASSWORD: ecommApp@1122
